name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-java@v3
        with:
          java-version: '11.0.4'
          distribution: zulu

      - name: Run tests
        run: |
          ./gradlew test
          ./gradlew jacocoTestReport

      - name: Upload coverage to gist
        run: |
          ./gradlew parseJacocoReport
          ./gradlew createGistPayload
          curl -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
               -H "Content-Type: application/json" \
               -X PATCH \
               --data @build/gist.json https://api.github.com/gists/2741eb65fdb9bdee723e50d7648294ed
